spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/belkhelfamehdi/config-server.git
          default-label: master

server:
  port: 8880
